openapi: 3.1.1
info:
  title: World One
  description: |
    This is a lil project for Sawyer.

    A timestamp with value 2200-01-01T00:00:00Z will indicate an unconfigured (end) value.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    variables:
      path:
        default: '/v1'
tags:
  - name: Eras
    description:
      Eras control configs and allow for soft-resets of the game state.
paths:
  '/v1/eras':
    get:
      tags:
        - Eras
      summary: Get all eras
      operationId: getAllEras
      security:
        - {}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                anyOf:
                  - type: array
                    items:
                      '$ref': '#/components/schemas/EraDTO'
  '/v1/eras/current':
    get:
      tags:
        - Eras
      summary: Get current era
      operationId: getCurrEra
      security:
        - {}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/EraDTO'
  '/v1/eras/rollover':
    post:
      tags:
        - Eras
      summary: Rollover eras
      description: |
        Terminate the current era, soft reset the game, and create a new era.

        If no current era exists, create the first era.
      operationId: rollover
      security:
        - {}
      parameters:
        - newEraName:
          name: newEraName
          in: query
          required: true
          schema:
            type: string
            examples:
              - "The new era"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      newEraDTO:
                        '$ref': '#/components/schemas/EraDTO'
                  - anyOf:
                    - type: object
                      properties:
                        prevEraDTO:
                          '$ref': '#/components/schemas/EraDTO'
                    - type: null
        '400':
          description: Bad Request, such as when the new era's name is blank or a duplicate
          content:
            text/plain:
              schema:
                type: string
                examples:
                  - Bad request, try again
components:
  schemas:
    EraDTO:
      type: object
      required:
      - id
      - name
      - startTime
      - endTime
      - createTime
      - updateTime
      properties:
        id:
          type: string
          examples:
            - "0"
        name:
          type: string
          examples:
            - The first Era
        startTime:
          type: string
          examples:
            - 2024-12-09T02:48:40.246181Z
        endTime:
          type: string
          examples:
            - 2200-01-01T00:00:00Z
        createTime:
          type: string
          examples:
            - 2024-12-09T02:48:40.246181Z
        updateTime:
          type: string
          examples:
            - 2024-12-09T02:48:40.246181Z
    Error:
      type: object
      description: RFC 7807 (https://datatracker.ietf.org/doc/html/rfc7807)
      properties:
        type:
          type: string
          examples:
            - https://example.com/errors/generic-error
        title:
          type: string
          examples:
            - Something went wrong here.
        status:
          type: integer
          format: int64
          examples:
            - 403
        detail:
          type: string
          examples:
            - Unfortunately, we can’t provide further information.

