// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Era struct {
	ID         int64
	Name       string
	StartTime  time.Time
	EndTime    time.Time
	CreateTime time.Time
	UpdateTime time.Time
}
